package com.iquenobot.orchestrator.domain.model;

public enum ActionType {
    SEND_TEXT,
    SEND_MEDIA,
    SEND_IMAGE,
    SEND_VIDEO,
    SEND_AUDIO,
    SEND_DOCUMENT,
    SEND_LOCATION,
    SEND_TEMPLATE,
    CREATE_LEAD,
    UPDATE_LEAD,
    CREATE_CONTACT,
    UPDATE_CONTACT,
    ASSIGN_AGENT,
    TRANSFER_CONVERSATION,
    ESCALATE_SUPERVISOR,
    TAG_CONVERSATION,
    CLOSE_CONVERSATION,
    WAIT_FOR_RESPONSE,
    SCHEDULE_MESSAGE,
    NO_ACTION,
    REGISTER_EVENT
}
