package com.iquenobot.sales.domain.model;

import com.iquenobot.shared.enums.QuoteStatus;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Filtering criteria for the quotes list. generatedBy is the UUID of the user
 * who created the quote; botGenerated=true filters quotes generated by the BOT
 * (createdBy is null).
 */
public record QuoteSearchCriteria(String query, String customer, String quoteNumber, String phone,
                                  LocalDateTime dateFrom, LocalDateTime dateTo,
                                  QuoteStatus status,
                                  UUID generatedBy, boolean botGenerated,
                                  BigDecimal minTotal, BigDecimal maxTotal) {
}
